name: Deploy to DEV
description: Deploy to DEV
inputs:
  S3_BUCKET_NAME:
    required: true
    description: The s3-bucket-name used to host website
  AWS_ACCESS_KEY_ID:
    required: true
    description: access key
  AWS_SECRET_ACCESS_KEY:
    required: true
    description: secret key

runs:
  using: composite
  steps:
    - name: Create Directory
      working-directory: ./
      shell: bash
      run: |
        mkdir ${{ inputs.S3_BUCKET_NAME }}

    - name: Download Zip
      uses: actions/download-artifact@v3
      with:
        name: package
    
    - name: Unzip 
      working-directory: ./
      shell: bash
      run: unzip package.zip -d ./${{ inputs.S3_BUCKET_NAME }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    
    - name: Deploy Code Build to S3 Bucket
      working-directory: ./
      shell: bash
      run: aws s3 sync ./${{ inputs.S3_BUCKET_NAME }} s3://${{ inputs.S3_BUCKET_NAME }}