name: Deployment Pipeline Angular
on:
  push:
    tags:
      - '*:+v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
    inputs:
      tags:
        description: Tag
        required: true 
        type: string
jobs:
  build:
    name: Build Angular Application
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop
      - name: Exit if not on develop branch
        if: endsWith(github.event.base_ref, 'develop') == false
        run: exit -1
      - name: Getting Enviromnet Variables
        run: |
          echo ${{ needs.tagging.outputs.TAG}}
      - name: Starting Angular Application Building
        uses: ./.github/actions/frontend/build-angular
  
  deploy-dev:
    name: Deploy to dev
    needs: [build]
    environment:
      name: dev
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop
      - name: Starting Angular Application Building
        uses: ./.github/actions/frontend/deploy
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

  deploy-test:
    name: Deploy to test
    needs: [build, deploy-dev]
    environment:
      name: test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop
      - name: Starting Angular Application Building
        uses: ./.github/actions/frontend/deploy
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}